### ISSUE TITLE
Extending Stack crashes when the stack value type is a Struct

### ISSUE THREAD

**Issue by DoctorWhoof** [blitz-research/monkey2#114]
This causes a fatal mx2cc error. Turning the "MyObject" struct into a class works fine.
Using v1.1.01, macOS.

```
#Import "<std>"
Using std..
 
Function Main()
 
	Local testStack := New SortingStack
	
	For Local n := 1 To 20
		Local newItem := New MyObject
		newItem.depth = Rnd( 0, 100 )
		testStack.Push( newItem )
	Next
	
	testStack.DepthSort()
	
	For Local n := Eachin testStack
		Print( n.depth )
	Next
	
End
 
 
Class SortingStack Extends Stack<MyObject>
	Method DepthSort()
		Sort( Lambda:Int( x:MyObject,y:MyObject )
			Return x.depth<=>y.depth
		End )
	End
End
 
 
Struct MyObject
	Field depth := 0
End
```

**Comment by blitz-research** [comment]
I've got an ugly as hell fix for this which I'll clean up soon.

In the meantime, try putting the struct in a separate file...

**Comment by blitz-research** [comment]
Should be working now.

**Comment by DoctorWhoof** [comment]
Almost working... but not quite. 
Still crashes if the struct contains an Image field, for some reason.

Here's some code:
`Namespace renderstack

#Import "<std>"
#Import "<mojo>"
Using std..
Using mojo..
 
Function Main()
	Local testStack := New TestStack
	
	For Local n := 1 To 20
		Local newItem := New TestItem
		testStack.Add( newItem, Rnd( 0, 100 ) )
	Next
		
	For Local n := Eachin testStack.items
		Print( n.depth )
	Next
End


Class TestStack
	Field items := New Stack< TestItem >
	Method Add( item:TestItem, depth:Float ) 
		item.depth = depth
		items.Push( item )
	End
End


Struct TestItem				'Change this to a Class and it will compile!
	Field depth:Int
	Field img: Image		'Comment out this line and it will compile!
	Field color: Color
End`
