### ISSUE TITLE
Add  JoystickDevice.Close() to allow plugging/unplugging of joysticks.

### ISSUE THREAD

**Issue by Difference** [blitz-research/monkey2#259]
Because mx2 caches open joysticks in Global _joysticks:[] it's not possible to reopen/detect new joysticks, once one has been opened. Adding Close() fixes this issue.

This also needs 

`Extern Function  SDL_SYS_JoystickClose:Void(joystick:SDL_Joystick Ptr)`

somewhere.

```monkey
	#rem monkeydoc Close a joystick device.
			
	@param index Joystick index.
	
	#end
	Function Close:Void( index:Int )
		Assert( index>=0 And index<8 )
	 	If _joysticks[index]
		 	SDL_JoystickClose( _joysticks[index]._joystick )
		 	_joysticks[index] = Null
		Endif
	End	```

**Comment by blitz-research** [comment]
When are you supposed to use Close?

There are actually some SDL events for dealing with joysticks being
added/removed - will have at look at these right now:

https://wiki.libsdl.org/SDL_JoyDeviceEvent?highlight=%28%5CbCategoryStruct%5Cb%29%7C%28CategoryEvents%29

**Comment by blitz-research** [comment]
Ok, had a play around with this and got joysticks 'auto closing'.

Also added JoystickAdded and JoystickRemoved globals to JoystickDevice -
see new joystick banana.

**Comment by Difference** [comment]
It's much better, but there is still a glitch:
With bananas/joystick.monkey2 (tested on Mac OS) do this:
Plug in joystickA, plug in joystickB, unPlug in joystickA.
MX now sees "two" joysticks, but they are both joystickB.
Plugging in joystickA again does not update joy 2, so both joysticks are still joystickB

I guess SDL moves the remaining joystick up to position  0, and nobody tells Monkey.

**Comment by Difference** [comment]
Almost perfect now, ( commit https://github.com/blitz-research/monkey2/commit/c4d4cb2c1cfc1dd39d584025ef64409f5b048e39 )
Hotdocking/undocking works, but the joystick0.Attached property, never goes from False to True
If app is started with Joystick(s) inserted, Attached shows true, on removal, shows False, but reDocking nevers shows True, even though joystick values shows up correctly on screen.

**Comment by blitz-research** [comment]
> Hotdocking/undocking works, but the joystick0.Attached property, never
goes from False to True

No, once joystick is unplugged, that's it. You need to reopen a joystick.

What could be done here is to associate the GUID to the joystick and
'retain' the closed joystick so it can be reused next time a device with
the same GUID is plugged in. This would be transparent and the effect would
indeed be for Attached to go to true when the same joystick was plugged in
again (even into a different port - may not be desired?).

But again, am I overcomplicating things? Do all joysticks REALLY have
unique GUIDs? What'd be really cool is for index to represent physical USB
port, but I can't see how that could work, and joysticks (on pc anyway)
seem to have a set 'order' - my xbox controller always inserts itself at
index 0 etc.

I'll try the GUID thing anyway...any other ideas?

**Comment by blitz-research** [comment]
Also, what do you think about renaming JoystickDevice to plain old
Joystick? I could add a deprecated alias for BW compatibility.

**Comment by blitz-research** [comment]
Try latest develop branch.

It attempts to 'remember' removed joysticks via their GUID, so Attached can
now go false->true. Not sure how useful it really is though, if someone's
removed a joystick wont it generally be because they want to swap it? Not
that I'm much of a PC game player these days though...

**Comment by blitz-research** [comment]
Ok, more work on this! Most problems appear to be solved via simple
AllocJoystick/FreeJoystick functions - have a look at joystick test in
bananas which attempts to duplicates possible realworld usage in a game.

You can still just go JoystickDevice.Get(0) etc for simple usage too.

Should AllocJoystick be in mojo?

**Comment by Difference** [comment]
As I understand it, the GUID is for a type of joystick, so if I have two PS3 controllers, they are likely to have the same GUID.

Renaming JoystickDevice sounds good, to keep on par with Keyboard, Touch, Mouse. 

Latest version looks good, I'll se if I can find some same GUID controllers, and report back after testing on WIndows, Mac OS, Android and Android TV.

**Comment by Difference** [comment]
Just tested two same type joysticks on Mac OS, and number of joysticks are correct, but Monkey only reads one, because they have the same GUID.

**Comment by Difference** [comment]
I've consulted an avid gamer that says hotdocking should work like this:
Plug in JoystickA = map it to p1
Plug in JoystickB = map it to p2
Unplug JoystickA = JoystickB stays assigned to P2
Unplug JoystickB, replug JoystickB, will assign it to P1

**Comment by Difference** [comment]
Changing bananas/joystick.monkey2 Global allocated to Map<JoystickDevice,Bool> seems produce the right behavior. 

[EDIT]: Only on Mac OS, fails on Windows

```monkey
Global alloced:=New Map<JoystickDevice,Bool>

Function AllocJoystick:JoystickDevice()
	
	For Local i:=0 Until JoystickDevice.NumJoysticks()
		
		Local joystick:=JoystickDevice.Open( i )
		If alloced.Contains( joystick ) Continue
		
		alloced[joystick]=True
		
		Return joystick
	Next
	
	Return Null
End

Function FreeJoystick( joystick:JoystickDevice )
	
	If joystick alloced.Remove( joystick )
End
```

**Comment by Difference** [comment]
After a little digging around, it seems to me AllocJoystick could  be replaced by calling  SDL_JoystickInstanceID , and Monkey JoystickDevice , have a property called something like InstanceID ?

Maybe JoystickDevice.Open() should be replaced with JoystickDevice.Get(instanceID), where instance id could be 0 if you didnt have one.

https://wiki.libsdl.org/SDL_JoystickInstanceID

Then we could store the InstanceID  in Player , and refind our joystick, without having to worry about index.

```
/*
 * Get the instance id for this opened joystick
 */
SDL_JoystickID
SDL_JoystickInstanceID(SDL_Joystick * joystick)
{
    if (!SDL_PrivateJoystickValid(joystick)) {
        return (-1);
    }

    return (joystick->instance_id);
}

/*
 * Find the SDL_Joystick that owns this instance id
 */
SDL_Joystick *
SDL_JoystickFromInstanceID(SDL_JoystickID joyid)
{
    SDL_Joystick *joystick = SDL_joysticks;
    while (joystick) {
        if (joystick->instance_id == joyid) {
            return joystick;
        }
        joystick = joystick->next;
    }

    return NULL;
}
```

**Comment by blitz-research** [comment]
Not really sure how this works in practice - can you post some pseudo code
like the joystick banana that shows it in action?

The point of the AllocJoystick is really just to make sure that once a
player is assigned a joystick, that joystick is not assigned to another
player and I don't see how this helps there.

When a joystick is attached/detached, all the indices for Open are
effectively rearranged so you can't Just Open() any old joystick if you
need to assign a joystick to a player as that joystick could already be in
use by another player. And you need to Open() a joystick before you can
even get it's instanceID...

[edit]
Think I see what you're getting at but I don't think it works.

The main problem IMO is really which joystick to Open() when you need to assign a joystick to a player, and  instanceID doesn't help here because you need to Open() before you can get instanceID.

But of course you could be trying to solve a different problem. Also, you seem to be using internal APIs and data structures so you could also know something I don't...
[/edit]

**Comment by Difference** [comment]
This is what I've come up with so far. It's tested on Mac OS, will test on Windows tomorrow.

It needs ```Function SDL_JoystickFromInstanceID:SDL_Joystick Ptr(joyid:Int)``` added to sdl2, because SDL_JOYDEVICEREMOVED event does not return joystick index, but rather InstanceID.

I've removed the _guidmap and the moving around of _joysticks[..n] in favor of 8 static slots, that can be empty or have a JoystickDevice in them.

The user must give an owner name, when using JoystickDevice.Get(), a unique playername or id will do.

Here is my new mojo.joystick.monkey2 and bananas/joystick.monkey2, based on your code

mojo joystick.monkey
```monkey

Namespace mojo.input

#rem monkeydoc Joystick hat directions.

| JoystickHat value	| 
|:------------------|
| Centered
| Up
| Right
| Down
| Left
| RightUp
| RightDown
| LeftUp
| LeftDown

#end
Enum JoystickHat	'SDL values...
	Centered=0
	Up=1
	Right=2
	Down=4
	Left=8
	RightUp=Right|Up
	RightDown=Right|Down
	LeftUp=Left|Up
	LeftDown=Left|Down
End

#rem monkeydoc The JoystickDevice class.
#end
Class JoystickDevice
	
	Global JoystickAttached:Void( index:Int )
	
	Field JoystickDetached:Void()
	
	#rem monkeydoc True if joystick is currently attached.
	#end
	Property Attached:Bool()
		
		Return _joystick<>Null
	End

	#rem monkeydoc Joystick device name.
	#end	
	Property Name:String()
		Return _name
	End
	
	#rem monkeydoc Joystick globally unique identifier.
	#end	
	Property GUID:String()
		Return _guid
	End
	
	Property InstanceID:Int()
		Return SDL_JoystickInstanceID(_joystick)	
	End Property 

	#rem monkeydoc The number of axes supported by the joystick.
	#end	
	Property NumAxes:Int()
		Return _numAxes
	End
	
	#rem monkeydoc The number of balls upported by the joystick.
	#end	
	Property NumBalls:Int()
		Return _numBalls
	End
	
	#rem monkeydoc The number of buttons supported by the joystick.
	#end	
	Property NumButtons:Int()
		Return _numButtons
	End
	
	#rem monkeydoc The number of hats supported by the joystick.
	#end	
	Property NumHats:Int()
		Return _numHats
	End
	
	#rem monkeydoc Gets joystick axis value in the range -1 to 1.
	#end	
	Method GetAxis:Float( axis:Int )
		
		If Not _joystick Return 0
		
		Return (Float(SDL_JoystickGetAxis( _joystick,axis ))+32768)/32767.5-1
	End
	
	#rem monkeydoc Gets joystick ball value.
	#end	
	Method GetBall:Vec2i( ball:Int )

		If Not _joystick Return Null
		
		Local x:Int,y:Int
		SDL_JoystickGetBall( _joystick,ball,Varptr x,Varptr y )
		Return New Vec2i( x,y )
	End

	#rem monkeydoc Gets joystick hat value.
	#end	
	Method GetHat:JoystickHat( hat:Int )

		If Not _joystick Return JoystickHat.Centered
		
		Return Cast<JoystickHat>( SDL_JoystickGetHat( _joystick,hat ) )
	End

	#rem monkeydoc Check up/down state of a button.
	#end
	Method ButtonDown:Bool( button:Int )
		
		If Not _joystick Return False
		
		Return SDL_JoystickGetButton( _joystick,button )
	End
	
	#rem monkeydoc Checks is a button has been pressed.
	#end
	Method ButtonPressed:Bool( button:Int )

		If Not _joystick Return False
		
		If ButtonDown( button )
			If _hits[button] Return False
			_hits[button]=True
			Return True
		Endif
		_hits[button]=False
		Return False
	End
	
	#rem monkeydoc Gets the number of joysticks attached.
	#end
	Function NumJoysticks:Int()
		Return Min( SDL_NumJoysticks(),8 )
	End

	#rem  monkeydoc @hidden
	#end	
	Function UpdateJoysticks()
		SDL_JoystickUpdate()
	End
	
	
	Field _ownername:String	
	
	#rem monkeydoc Gets an attached joystick and assigns an identifyer to it.
	
	
	@param ownername Name of the owner. Should be uniqe.

	#end
 
	Function Get:JoystickDevice( ownername:String ) 
		
		' look through slots
		For Local i:= 0 Until 8
			If  _joysticks[i]?._ownername  =  ownername Return _joysticks[i]
		Next
	
		' count open joys
		Local opencount:Int
		For Local i:= 0 Until 8
			If _joysticks[i]  opencount+=1
		Next
		
		If opencount>= NumJoysticks() Return Null	' should not happen
 		
 		For Local i:= 0 Until 8
			If Not _joysticks[i] ' available slot
				
				Local sdlJoystick:=SDL_JoystickOpen( opencount )
				If Not sdlJoystick Return Null
			
				_joysticks[i]=New JoystickDevice( sdlJoystick )
				_joysticks[i]._ownername = ownername
	 
		 		'Print "Slot " + i + "now belongs to: " + _joysticks[i]._ownername  + "Joy Port Nr " + opencount
			
				Return _joysticks[i]			
			Endif
					
		Next			

		
		Return Null
	
	
	End Function
	
	

	Internal
	
	Function SendEvent( event:SDL_Event Ptr )
	
		Select event->type
		Case SDL_JOYDEVICEADDED
			
			Local jevent:=Cast<SDL_JoyDeviceEvent Ptr>( event )
			
			Local index:=jevent->which
			
			JoystickAttached( index )
			
		Case SDL_JOYDEVICEREMOVED
			
			Local jevent:=Cast<SDL_JoyDeviceEvent Ptr>( event )
			
			Local index:=jevent->which
			
			Local sdlJoystick:= SDL_JoystickFromInstanceID(index) ' index is an instanceid, so we look up the joystick
				
			For Local i:=0 Until 8 ' find it's slot and remove it.
				If _joysticks[i]?._joystick = sdlJoystick
					_joysticks[i]?.Detach()			
					_joysticks[i]=Null
				Endif
						
			Next
 				
		End
	
	End
	
	Private
	

	
	Global _joysticks:=New JoystickDevice[8]
	
	Field _guid:String
	Field _name:String
	Field _numAxes:Int
	Field _numBalls:Int
	Field _numButtons:Int
	Field _numHats:Int
	
	Field _joystick:SDL_Joystick Ptr
	Field _hits:=New Bool[32]
	
	
	
	
	Function GetGUID:String( joystick:SDL_Joystick Ptr )
		Local buf:=New Byte[64]
		Local guid:=SDL_JoystickGetGUID( joystick )
		SDL_JoystickGetGUIDString( guid,Cast<libc.char_t Ptr>( buf.Data ),buf.Length )
		buf[buf.Length-1]=0
		Return String.FromCString( buf.Data )
	End
	
	Method New( joystick:SDL_Joystick Ptr )

		Attach( joystick )
		
		_guid=GetGUID( joystick )
		_name=String.FromCString( SDL_JoystickName( _joystick ) )
		_numAxes=SDL_JoystickNumAxes( _joystick )
		_numBalls=SDL_JoystickNumBalls( _joystick )
		_numButtons=SDL_JoystickNumButtons( _joystick )
		_numHats=SDL_JoystickNumHats( _joystick )
	End
	
	Method Attach( joystick:SDL_Joystick Ptr )
		
		libc.memset( _hits.Data,0,32 )
		
		_joystick=joystick
	End
	
	Method Detach()
		
		If Not _joystick Return
		
		SDL_JoystickClose( _joystick )
		Print "SDL_JoystickClose"
		_joystick=Null
		
		Local detached:=JoystickDetached
		
		JoystickDetached=Null
		
		detached()
	End

End

```
bananas/joystick.monkey2
```monkey

Namespace test

#Import "<std>"
#Import "<mojo>"

Using std..
Using mojo..

 

 
'***** Simple player class *****

Class Player

	Field id:Int
	Field joystick:JoystickDevice
	
	Global used:=New StringMap<Bool>
	
	Method New( id:Int )
		Self.id=id
		Self.joystick=JoystickDevice.Get("Player"+id) 'AllocJoystick()
	End
	
	Method Update( canvas:Canvas )
		
		canvas.DrawText( "Player "+id,0,0 )
		
		'update joystick state
		If joystick And Not joystick.Attached
'			FreeJoystick( joystick )
			joystick=Null
		Endif
		
		If Not joystick
			joystick = JoystickDevice.Get("Player"+id)
			If Not joystick
				canvas.DrawText( "No Joystick available",0,16 )
				Return
			Endif
		Endif

		'draw joystick info.		
		canvas.DrawText( "Name="+joystick.Name,0,16 )
		
		For Local axis:=0 Until 6
			canvas.DrawText( "Axis "+axis+"="+joystick.GetAxis( axis ),0,axis*16+32 )
		Next
	
	End
	
End

'***** MainWindow *****

Class MainWindow Extends Window
	
	Field players:=New Player[4]

	Method New()
		Super.New( "Joystick test",640,480 )
		
		For Local i:=0 Until 4
			players[i]=New Player( i )
		Next
		
	End

	Method OnRender( canvas:Canvas ) Override
	
		RequestRender()
	
		canvas.DrawText( "NumJoysticks="+JoystickDevice.NumJoysticks(),0,0 )
		
		canvas.PushMatrix()
		
		canvas.Translate( 0,16 )
		
		For Local i:=0 Until 4
			
			players[i].Update( canvas )
			
			canvas.Translate( 0,144 )
		Next
		
		canvas.PopMatrix()
		
	End
	
End

Function Main()

	New AppInstance
	
	New MainWindow
	
	App.Run()
	
End
```

**Comment by blitz-research** [comment]
I get the original problem with this, ie: if I start out with 2 joysticks
plugged in and remove player 1's joystick and reattach it, I get a
duplicated joystick for both players. Works OK for player 2 though. I'm on
a PC too.

I think the problem is that when I plugin in my xbox 360 controller, it is
always attached at index 0 (not sure what the story on the Mac is), but
your code always SDL_JoystickOpens the 'next' joystick based on opencount.
This is why I ended up shifting the array elements around in the
attached/detached events - joysticks seem to have their own 'hardcoded'
order.

> Function SDL_JoystickFromInstanceID:SDL_Joystick Ptr(joyid:Int)

Useful! Wonder where that went in sdl2? Will add it permanently anyway. My
old code was in fact finding the correct joystick for removal though, just
in a slightly roundabout way.

**Comment by blitz-research** [comment]
Have a pretty good solution working now, seems to work the same on both PC
and MAC.

You still you JoystickDevice.Open( index:int ) except it works a lot like
your approach, so index:Int is a lot more like playerId.

I also added a Close() method when a player quits a gameor changes to
control method to keyboard and you want their joystick to become available
to a different player.

You should generally try to match each Open() with a Close(), although you
don't strictly need a Close() when a joystick is detached.

Removed attached/detached signals for now too until we decide we're happy
with the state of things!

**Comment by Difference** [comment]
First; MANY  thanks for your dedication to this issue! :-)

I've tried out your new code without success. It actually ends up losing all contact to all joysticks.

I've also tried a gazillion other solutions, 

There seems to be several problems, one of them being that the 

```	
Case SDL_JOYDEVICEADDED
		Local jevent:=Cast<SDL_JoyDeviceEvent Ptr>( event )
		Local sdlindex:=jevent->which
```
is always zero.

Comparing joystick pointers fails too, and getting and comparing the InstanceIDs is futile, because of jevent->which being always zero.

I'm suspecting some of this comes from the joysticks being in a usb hub, but since that's no problem on Mac, that can't be all that is wrong.


I've had several attempts, that where not too shabby, but still not solving it correctly. I might have a go more at it, because it's really frustrating, that such a core feature for making games, dosen't "just work".

**Comment by blitz-research** [comment]
> First; MANY thanks for your dedication to this issue! :-)

No problem. It's the sort of thing I've usually left up to end users, but
this is actually really freaking HARD so I'm feeling guilty now!

> I've tried out your new code without success. It actually ends up losing
all contact to all joysticks.

I did have a bit of a drama getting controllers going on mac, but
eventually installed an xbox360 controller driver and found a
gamecontroller 'viewer' app.

I am plugging game controllers directly into my mac mini's USB ports - have
you tried doing that instead of using a hub? I have had a TON of problems
with hubs over the years...

The gamecontroller viewer app I used is called 'Controllers Lite' and I
found it on the macos app store. Might want to give that a go too.

> Local jevent:=Cast<SDL_JoyDeviceEvent Ptr>( event )
Local sdlindex:=jevent->which

This stuff appears to behave subtly differently on pc/mac. On pc, my xbox
360 controller is always added at index 0, while on mac joysticks seem to
always be added 'in order' (so I see why your previous version worked now).
The array shift up/down code should take care of this though.

What do you mean by 'losing all contact to all joysticks'? Are you getting
spurious 'SDL_JOYDEVICEREMOVED' events, or do they just stop responding?

[EDIT]I have just found a bug in the module code, try the latest develop
branch!

**Comment by Difference** [comment]
Just tried  the lastest ( https://github.com/blitz-research/monkey2/commit/69d62258dd12c8d88b346225d90f66b7e1ffb298 ) on Mac OS (with USB Hub) and Windows 10, (without USB hub.)

Mac OS works perfectly, including letting PS3 controller work through Bluetooth.

Windows (with and without USB hub) works when the controllers have different GUIDs, but messes up, and eventually crashes with same GUID controllers. ( I use two of these: https://www.aliexpress.com/item/Newest-Arrival-Game-pad-USB-Wired-Joypad-Gamepad-Controller-For-Microsoft-Game-System-PC-For/32776663353.html ) 

The crash don't let me debug it, Joystick.exe just hangs.
I notice you don't  
```
// Close if opened
    if (SDL_JoystickGetAttached(joy)) {
        SDL_JoystickClose(joy);
    }
```

and according to https://wiki.libsdl.org/SDL_JoystickOpen, I think we are supposed to do that. In my tests, I had crashes when not doing that.

Launching with both controllers plugged in works. 
Plugging in JoyA, then  JoyB works, unplugging/replugging JoyA or JoyB, gives varied results, like loosing input from one, mapping all players to the same controller or shifting the controller to another player.

For testing the controlles outside Monkey I use http://www.generalarcade.com/gamepadtool/ . That can also give you an SDL compatible mapping string, to save a joystick mapping in.

**Comment by Difference** [comment]
I just noticed joystick.exe spits out a constant flow of 

> ***** JoystickDevice.Open() Error: device GUID already in use by open joystick! *****
***** JoystickDevice.Open() Error: SDL_JoystickOpen failed! *****

maybe overfilling the debuglog, is the cause of the crash? ([EDIT]: I've left it running a long time but no crash yet so maybe not)

Anyway: Two identical GUIDs are not an error, they just represent the same joystick model.

**Comment by Difference** [comment]
This is my best version for Windows and MacOS yet!
 It gives up on trying to solve the SDL "failure to distinguish joysticks" problem, but seems ok otherwise, except I did get an "memory acces error" once in app.monkey when quitting at 

[EDIT]: Updated with better Purge() (moved to Open()) , now also solid on MacOS :-) 
[EDIT2]: When pluggin/unpluggin'  I get a memory access  at: Local sdljoystick:=  SDL_JoystickOpen( k ) sometimes.
I can't see why that would happen, when I'm in the For Local k:Int = 0 Until NumJoysticks() range.
[EDIT3]: seems fixed by adding If Not NumJoysticks() Return Null 
[EDIT4]: Changed if_joystick checks to Attached, and added extra search condition + reinstated Purge in () Case SDL_JOYDEVICEREMOVED



```
Method DispatchEvents()

	Local event:SDL_Event

	While SDL_PollEvent( Varptr event )

		DispatchEvent( Varptr event )
```
```monkey
 
Namespace difference.joystick
#Import "<sdl2>"

Using sdl2..


#rem 
	alternative joysick module for monkey2 mojo.input.joystick
	to use put: 
	#Import "joystick"
	Alias JoystickDevice:difference.joystick.JoystickDevice	
	at the top of your code
#end


#rem monkeydoc Joystick hat directions.

| JoystickHat value	| 
|:------------------|
| Centered
| Up
| Right
| Down
| Left
| RightUp
| RightDown
| LeftUp
| LeftDown

#end
Enum JoystickHat	'SDL values...
	Centered=0
	Up=1
	Right=2
	Down=4
	Left=8
	RightUp=Right|Up
	RightDown=Right|Down
	LeftUp=Left|Up
	LeftDown=Left|Down
End

#rem monkeydoc The JoystickDevice class.
#end
Class JoystickDevice
	
	Global JoystickAttached:Void( index:Int )
	
	Field JoystickDetached:Void()
	
	#rem monkeydoc True if joystick is currently attached.
	#end
	Property Attached:Bool()
		If not _joystick Return False
		If Not SDL_JoystickGetAttached(_joystick) 
			Return False
		Endif 	 
		Return True 
	End

	#rem monkeydoc Joystick device name.
	#end	
	Property Name:String()
		Return _name
	End
	
	#rem monkeydoc Joystick globally unique identifier.
	#end	
	Property GUID:String()
		Return _guid
	End
	
	Property InstanceID:Int()
		Return SDL_JoystickInstanceID(_joystick) 
	End Property 

	#rem monkeydoc The number of axes supported by the joystick.
	#end	
	Property NumAxes:Int()
		Return _numAxes
	End
	
	#rem monkeydoc The number of balls upported by the joystick.
	#end	
	Property NumBalls:Int()
		Return _numBalls
	End
	
	#rem monkeydoc The number of buttons supported by the joystick.
	#end	
	Property NumButtons:Int()
		Return _numButtons
	End
	
	#rem monkeydoc The number of hats supported by the joystick.
	#end	
	Property NumHats:Int()
		Return _numHats
	End
	
	#rem monkeydoc Gets joystick axis value in the range -1 to 1.
	#end	
	Method GetAxis:Float( axis:Int )
		
		If Not Attached Return 0
		
		Return (Float(SDL_JoystickGetAxis( _joystick,axis ))+32768)/32767.5-1
	End
	
	#rem monkeydoc Gets joystick ball value.
	#end	
	Method GetBall:Vec2i( ball:Int )

		If Not Attached Return Null
		
		Local x:Int,y:Int
		SDL_JoystickGetBall( _joystick,ball,Varptr x,Varptr y )
		Return New Vec2i( x,y )
	End

	#rem monkeydoc Gets joystick hat value.
	#end	
	Method GetHat:JoystickHat( hat:Int )

		If Not Attached Return JoystickHat.Centered
		
		Return Cast<JoystickHat>( SDL_JoystickGetHat( _joystick,hat ) )
	End

	#rem monkeydoc Check up/down state of a button.
	#end
	Method ButtonDown:Bool( button:Int )
		
		If Not Attached Return False
		
		Return SDL_JoystickGetButton( _joystick,button )
	End
	
	#rem monkeydoc Checks is a button has been pressed.
	#end
	Method ButtonPressed:Bool( button:Int )

		If Not Attached Return False
		
		If ButtonDown( button )
			If _hits[button] Return False
			_hits[button]=True
			Return True
		Endif
		_hits[button]=False
		Return False
	End
	
	#rem monkeydoc Gets the number of joysticks attached.
	#end
	Function NumJoysticks:Int()
		Return Min( SDL_NumJoysticks(),8 )
	End

	#rem  monkeydoc @hidden
	#end	
	Function UpdateJoysticks()
		SDL_JoystickUpdate()
	End
	

	
	#rem monkeydoc Gets an attached joystick and assigns an identifyer to it.
	
	
	@param ownername Name of the owner. Should be uniqe.

	#end
 
 
 
	Function Open:JoystickDevice( index:Int ) 
		
		Global lastjoyCount:Int 
		
	 	If sticks.Contains(index)
		 	If sticks[index].Attached Return sticks[index]
		 	Purge()
		 	JoysDirty = -1
 		Endif
 		
 		If lastjoyCount <> NumJoysticks() JoysDirty = 1 ' force an update becuse something happened
 		
		If JoysDirty=0 Return Null
		
		If Not NumJoysticks() Return Null 
	
	
		lastjoyCount  = NumJoysticks()
	
		For Local k:Int = 0 Until NumJoysticks()
	
			Local sdljoystick:=  SDL_JoystickOpen( k )
			
			If sdljoystick 
				
				Local present:Bool 
				'do we have it already?
				For Local pstick:= Eachin sticks
					If pstick.Value._joystick = sdljoystick
						present = True 
						Print "Sorry already there " + k 	
					Endif 		
				Next  	
				If Not present 
					Print "Adding to sticks " +  k
					Local stick:= New JoystickDevice(sdljoystick)
					sticks.Add(index,stick)
					Return stick
				Endif 
			Endif	
		Next 
			
 
 
		JoysDirty = 0
			 
			 
 '		Print "sorry ," + index + " we have no sticks for you. We have " + sticks.Length  	 
			 
		Return Null 
		
 
	
	
	End Function
	
	Global sticks:= New IntMap<JoystickDevice>

	Internal
	
	
	Global JoysDirty:Int = 999
	
	Function Purge:Void()
		
		
		Local removelist:= New IntList
 
		For Local stick:= Eachin sticks	
			If Not stick.Value.Attached
				stick.Value.Detach()
				removelist.Add(stick.Key)
			Endif 	
		Next 	
	 
	 	For Local stickid:= Eachin removelist
				
			sticks.Remove(stickid)
		Next		
 
		
	End Function	
	
	
	Function SendEvent( event:SDL_Event Ptr )
	
		Select event->type
		Case SDL_JOYDEVICEADDED
			
			Local jevent:=Cast<SDL_JoyDeviceEvent Ptr>( event )
			
			Local index:=jevent->which
			
			JoysDirty = 1
			
			
		Case SDL_JOYDEVICEREMOVED
			
			Local jevent:=Cast<SDL_JoyDeviceEvent Ptr>( event )
			
			Local index:=jevent->which
			
			Purge() ' we do it in Open() too
			
			JoysDirty = -1	' could be any value
			
		End
	
	End
	
	Private
	
	Global _joysticks:=New JoystickDevice[8]
	
	Field _guid:String
	Field _name:String
	Field _numAxes:Int
	Field _numBalls:Int
	Field _numButtons:Int
	Field _numHats:Int
	
	Field _joystick:SDL_Joystick Ptr
	Field _hits:=New Bool[32]
	
 
	
	Function GetGUID:String( joystick:SDL_Joystick Ptr )
		Local buf:=New Byte[64]
		Local guid:=SDL_JoystickGetGUID( joystick )
		SDL_JoystickGetGUIDString( guid,Cast<libc.char_t Ptr>( buf.Data ),buf.Length )
		buf[buf.Length-1]=0
		Return String.FromCString( buf.Data )
	End
	
	Method New( joystick:SDL_Joystick Ptr )

		Attach( joystick )
		
		_guid=GetGUID( joystick )
		_name=String.FromCString( SDL_JoystickName( _joystick ) )
		_numAxes=SDL_JoystickNumAxes( _joystick )
		_numBalls=SDL_JoystickNumBalls( _joystick )
		_numButtons=SDL_JoystickNumButtons( _joystick )
		_numHats=SDL_JoystickNumHats( _joystick )
		
	 
	End
	
	Method Attach( joystick:SDL_Joystick Ptr )
		
		libc.memset( _hits.Data,0,32 )
		
		_joystick=joystick
	End
	
		Method Detach()
		
		If Not _joystick Return
		If  SDL_JoystickGetAttached(_joystick)
			SDL_JoystickClose( _joystick )
			Print "SDL_JoystickClose"
		Endif
		_joystick=Null
		

	End

End 


```

**Comment by blitz-research** [comment]
> ***** JoystickDevice.Open() Error: device GUID already in use by open
joystick! *****
> ***** JoystickDevice.Open() Error: SDL_JoystickOpen failed! *****

Fortunately, these were added by me and can be turned off, just set DEBUG
and PARANOID to False at top of module source file.

I mistunderstood the GUID, I thought it'd be different for *every* device
in the system, like ethernet cards! But I only use GUIDs as a sort of cross
check anyway - disabling PARANOID should ignore them entirely.

SDL_JoystickOpen failing is a bit more serious, but one thing at a time...

Also, I've posted some questions here, you might want to join in!

https://discourse.libsdl.org/t/joystick-questions/23356

**Comment by Difference** [comment]
I think SDL_JoystickOpen failing was due to poor coding on my part, I should have checked Numjoysticks() first. (see EDIT3 above. )

I'm changing the If  _joystick checks to If Attached(), because I put a  SDL_JoystickGetAttached in that, together with the  If  _joystick check. I'm going with my version for now, because It gives the most stable results. I'll report back on stability and how it all works on Android and Android TV soon.

**Comment by blitz-research** [comment]
Ok will close this now!

I have pushed one final version you might want to try - works flawlessly
here on PC, Mac, Linux, also renamed JoystickDevice to plain Joystick and
added an alias for BW compatibility.

**Comment by Difference** [comment]
Still crashing on Windows 10, without debugger showing where when unplugging/plugging devices.

I notice your started working on SDL Gamecontroller. Will that bypass this whole issue, or will Joystick still be needed?

I've been rethinking what could be done, and reading that people seem to have success, when not polling joysticks (potentially polling an unattached device I guess), but rather only reading joystick events. Now that I understand the issues with SDL_Joystick a little better, I might have a go at that, but If GameController superseds Joystick, that will be a much more convenient solution.

**Comment by blitz-research** [comment]
I suspect you'll have the same issue with gamecontroller as it uses
joystick behind the scenes. Everything's working fine here though so I'm
gonna leave this for a while as I need to get on with other stuff. Feel
free to reopen this if you get any more ideas though.
