### ISSUE TITLE
Cannot use function in Super.New() method

### ISSUE THREAD

**Issue by wiebow** [blitz-research/monkey2#39]
I am trying to call a function when creating an extended class, and calling the Super.New() method. This result in a Memory Access Violation, while the base class does have the New() method that accept an image:

	Method New()
		Super.New( GetImage("sprites",1) )
	End Method

GetImage(name, frame) is a function that will return an image from an array.

While this works, where images is a global variable, set to an image:

	Method New()
		Super.New(images)
	End Method

**Comment by wiebow** [comment]
Is this intended behaviour @blitz-research ?

**Comment by blitz-research** [comment]
No, MAV's aren't intended behaviour!

Should be fixed now.

**Comment by wiebow** [comment]
I assume the fix has not been uploaded yet, as the problem is still there.

**Comment by blitz-research** [comment]
Have you done an updatemx2cc?

**Comment by blitz-research** [comment]
...and if it's still happening can you post some runnable code? I threw
something together for testing that works, but it may not be the same...

**Comment by blitz-research** [comment]
Here's the sample I used, which used to crash like crazy...


Class T
Field str:String
Method New( str:String )
Self.str=str
Print "T.New("+str+")"
End
End

Function F:T( str:String )
Return New T( str )
End

Class C

Method New( t:T )
Print "Here! t.str="+t.str
End
End
Class D Extends C

Method New( str:String )
Super.New( F( str ) )
End
End

Function Main()

New D( "Hello!" )
End

**Comment by wiebow** [comment]
Apparently updateall.sh does not update mx2cc?  I performed the update as you suggested and now it's compiling and running!!! Thanks.

**Comment by blitz-research** [comment]
Yay!

Yeah, only 'tagged' releases have prebuilt binaries in them.

It's tricky to add updatemx2cc to rebuildall, as depending on what I've
been playing with you either need to build modules first or mx2cc.

Should add this to the readme...
