### ISSUE TITLE
SQLite demo fails to build on Linux

### ISSUE THREAD

**Issue by jondecker76** [blitz-research/monkey2#470]
`Mx2cc version 1.1.15

***** Making app '/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.monkey2' (linux release x64 gcc) *****

Parsing...
Semanting...
Translating...
Compiling...
Linking /home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.products/Linux/Sqlitetest...
Build error: System command failed:

g++  -s -O3 -o "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.products/Linux/Sqlitetest" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r5b58089e.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r73a64ed5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r4d8c9f55.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/r897528f5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/bananas/sqlitetest/sqlitetest.buildv1.1.15/linux_release/build/sqlitetestb4f98a14.cpp.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a" "/home/viavacavi/Dropbox/monkey2/modules/libc/libc.buildv1.1.15/linux_release/libc.a" "/home/viavacavi/Dropbox/monkey2/modules/monkey/monkey.buildv1.1.15/linux_release/monkey.a" 

/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `pthreadMutexTry':
sqlite3.c:(.text+0x44c5): undefined reference to `pthread_mutex_trylock'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbeIncrFree':
sqlite3.c:(.text+0xb908): undefined reference to `pthread_join'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbePmaReaderNext':
sqlite3.c:(.text+0xecca): undefined reference to `pthread_join'
/usr/bin/ld: sqlite3.c:(.text+0xece8): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `pthreadMutexAlloc':
sqlite3.c:(.text+0x120b7): undefined reference to `pthread_mutexattr_init'
/usr/bin/ld: sqlite3.c:(.text+0x120c4): undefined reference to `pthread_mutexattr_settype'
/usr/bin/ld: sqlite3.c:(.text+0x120d7): undefined reference to `pthread_mutexattr_destroy'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbeSorterFlushPMA':
sqlite3.c:(.text+0x13be4): undefined reference to `pthread_join'
/usr/bin/ld: sqlite3.c:(.text+0x13d18): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `sqlite3VdbeSorterReset':
sqlite3.c:(.text+0x164ea): undefined reference to `pthread_join'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `vdbeMergeEngineInit':
sqlite3.c:(.text+0x1d3a8): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlError':
sqlite3.c:(.text+0x29d8f): undefined reference to `dlerror'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `sqlite3VdbeExec':
sqlite3.c:(.text+0x84e97): undefined reference to `pthread_join'
/usr/bin/ld: sqlite3.c:(.text+0x89da2): undefined reference to `pthread_create'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlClose':
sqlite3.c:(.text+0x4a24): undefined reference to `dlclose'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlSym':
sqlite3.c:(.text+0x4a37): undefined reference to `dlsym'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlOpen':
sqlite3.c:(.text+0x4a49): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status

***** Fatal mx2cc error *****

Internal mx2cc build error
`

**Comment by jondecker76** [comment]
doing some reading, it seems to have something to do with -ldl linker flag, but I can't see where I need to add that in

**Comment by blitz-research** [comment]
Hi,

I've pushed a fix for this to the develop branch.

**Comment by jondecker76** [comment]
Thanks for looking at this!

Unfortunately I still can't compile the example.  Definitely a lot less errors, but it still doesn't run for me.  I've tried adding -ldl flag also with no luck
`
Mx2cc version 1.1.15

***** Making app '/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.monkey2' (linux release x64 gcc mx) *****

Parsing...
Semanting...
Translating...
Compiling...
Linking /home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.products/Linux/Test1...
Build error: System command failed:

g++ -lpthread -s -O3 -o "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.products/Linux/Test1" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/r5b58089e.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/re1704349.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/rb884b1f5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/rc349c855.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/test1534f6eb4.cpp.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a" "/home/viavacavi/Dropbox/monkey2/modules/libc/libc.buildv1.1.15/linux_release_mx/libc.a" "/home/viavacavi/Dropbox/monkey2/modules/monkey/monkey.buildv1.1.15/linux_release_mx/monkey.a" -lpthread

/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlError':
sqlite3.c:(.text+0x29d8f): undefined reference to `dlerror'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlClose':
sqlite3.c:(.text+0x4a24): undefined reference to `dlclose'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlSym':
sqlite3.c:(.text+0x4a37): undefined reference to `dlsym'
/usr/bin/ld: /home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a(sqlite3e31ba218.c.o): in function `unixDlOpen':
sqlite3.c:(.text+0x4a49): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status


***** Fatal mx2cc error *****

Internal mx2cc build error`

**Comment by jondecker76** [comment]
A little more info...
If I add -ldl to the end of the g++ command, then I can compile from the command line, but not from within Ted2Go.

This fails:
`g++  -s -O3 -o "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.products/Linux/Test1" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/r5b58089e.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/re1704349.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/rb884b1f5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/rc349c855.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/test1534f6eb4.cpp.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a" "/home/viavacavi/Dropbox/monkey2/modules/libc/libc.buildv1.1.15/linux_release_mx/libc.a" "/home/viavacavi/Dropbox/monkey2/modules/monkey/monkey.buildv1.1.15/linux_release_mx/monkey.a" -lpthread`

But this builds successfully:
`g++  -s -O3 -o "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.products/Linux/Test1" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/r5b58089e.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/re1704349.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/rb884b1f5.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/rc349c855.cpp_r.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/tests/test1.buildv1.1.15/linux_release_mx/build/test1534f6eb4.cpp.o" "/home/viavacavi/Dropbox/monkey2/modules/sqlite/sqlite.buildv1.1.15/linux_release_mx/sqlite.a" "/home/viavacavi/Dropbox/monkey2/modules/libc/libc.buildv1.1.15/linux_release_mx/libc.a" "/home/viavacavi/Dropbox/monkey2/modules/monkey/monkey.buildv1.1.15/linux_release_mx/monkey.a" -lpthread -ldl`

I'm not sure why, but adding -ldl to the beginning of the command string fails, it only seems to work when it is at the end

**Comment by XANOZOID** [comment]
@jondecker76 did you clean your build folder before compiling? If @blitz-research pushed a fix but didn't change the monkey2 version then not clearing the output folder could cause some problems.

If you didn't try that hopefully this makes a difference . . .

**Comment by blitz-research** [comment]
Oops, may bad, should be fixed now...
